#!/bin/bash

get_record_info() {
    domain=$1
    subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        result=$(dig +short $sub.$domain | awk -v sub=$sub '{print sub"."$2}')
        record_type=$(echo $result | awk '{print $2}')
        destination=$(echo $result | awk '{print $NF}')

        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

if [ $# -lt 1 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

get_record_info $1 $2
